# Generated by Django 2.1 on 2018-08-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('variety', models.CharField(default=None, max_length=60, null=True)),
                ('type', models.CharField(choices=[('flour', 'flour'), ('water', 'water'), ('liquid', 'liquid'), ('dry', 'other')], max_length=60)),
                ('hash32', models.IntegerField(default=True)),
            ],
        ),
    ]
