# Generated by Django 2.1 on 2018-08-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20180813_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='hash32',
            field=models.BigIntegerField(null=True),
        ),
    ]
