# Generated by Django 2.1 on 2018-08-14 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_rename-ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='type',
            field=models.CharField(choices=[
                ('flour', 'flour'), ('water', 'water'), ('liquid', 'liquid'),
                ('other', 'other'), ('meal', 'meal'), ('malt', 'malt'),
                ('fat', 'fat'), ('seed', 'seed')
                ], max_length=60),
        ),
    ]
