# Generated by Django 2.1 on 2018-08-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_add-basic-ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='type',
            field=models.CharField(choices=[('flour', 'flour'), ('water', 'water'), ('liquid', 'liquid'), ('fat', 'fat'), ('seed', 'seed'), ('other', 'other'), ('meal', 'meal'), ('malt', 'malt')], max_length=60),
        ),
        migrations.AlterModelTable(
            name='ingredient',
            table='ingredient',
        ),
    ]
