# Generated by Django 2.1 on 2018-08-14 18:11

from django.db import migrations
import custom_fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_rename-recipes-ingredient-table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='hash32',
            field=custom_fields.UnsignedIntegerField(null=True),
        ),
    ]
