# Generated by Django 2.1 on 2018-10-13 12:47

import custom_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_bootstrap-model-relationships'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='instruction',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='mixture',
        ),
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.ManyToManyField(db_table='recipe_instruction', to='recipes.Instruction'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='mixtures',
            field=models.ManyToManyField(db_table='recipe_mixture', to='recipes.Mixture'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='hash32',
            field=custom_fields.UnsignedIntegerField(null=True, unique=True),
        ),
    ]
