# Generated by Django 2.1 on 2018-10-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_rename-recipe-fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='mixture',
            name='mixtures',
            field=models.ManyToManyField(to='recipes.Mixture'),
        ),
    ]
