# Generated by Django 2.1 on 2018-10-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_mixture-add-recursive-relationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mixture',
            name='mixtures',
            field=models.ManyToManyField(related_name='_mixture_mixtures_+', to='recipes.Mixture'),
        ),
    ]
