# Generated by Django 2.2.4 on 2019-09-16 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_auto_20190913_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instruction',
            old_name='label',
            new_name='title',
        ),
    ]
