# Generated by Django 2.2.4 on 2019-09-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_auto_20190916_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='mixture',
            name='dependent',
            field=models.BooleanField(default=False),
        ),
    ]
