# Generated by Django 2.2.4 on 2019-09-30 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_mixture_dependent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mixture',
            name='dependent',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='mixtures',
        ),
        migrations.AddField(
            model_name='recipe',
            name='deductible',
            field=models.ManyToManyField(db_table='recipe_deductible', related_name='recipes', to='recipes.Mixture'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='final',
            field=models.ForeignKey(db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='recipes.Mixture'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='overall',
            field=models.ForeignKey(db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.Mixture'),
        ),
    ]
