# Generated by Django 2.2.4 on 2019-10-04 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_auto_20190930_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='final_factor',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='overall_factor',
            field=models.FloatField(default=1.0),
        ),
        migrations.CreateModel(
            name='RecipeMixture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.FloatField(default=1.0)),
                ('mixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Mixture')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe')),
            ],
            options={
                'db_table': 'recipe_deductible_new',
            },
        ),
    ]
