# Generated by Django 2.2.4 on 2019-10-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):


    dependencies = [
        ('recipes', '0017_auto_20191004_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='deductible',
        ),
        migrations.AlterModelTable(
            name='recipemixture',
            table='recipe_deductible',
        ),
        migrations.AddField(
            model_name='recipe',
            name='deductible',
            field=models.ManyToManyField(related_name='recipes', through='recipes.RecipeMixture', to='recipes.Mixture'),
        ),
    ]
