# Generated by Django 2.2.4 on 2019-10-04 14:50

import custom_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0018_extend_recipe_deductible_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mixture',
            name='hash32',
            field=custom_fields.UnsignedIntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mixture',
            name='mixture',
            field=models.ManyToManyField(related_name='from_mixture', to='recipes.Mixture'),
        ),
    ]
