# Generated by Django 2.2.4 on 2019-10-04 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0019_loose_symmetry_mixture_mixture'),
    ]

    operations = [
        migrations.CreateModel(
            name='MixtureRecursive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.FloatField(default=1.0)),
            ],
            options={
                'db_table': 'mixture_nest',
            },
        ),
        migrations.RemoveField(
            model_name='mixture',
            name='mixture',
        ),
        migrations.AddField(
            model_name='mixture',
            name='mixture',
            field=models.ManyToManyField(related_name='primary_mixture', through='recipes.MixtureRecursive', to='recipes.Mixture'),
        ),
        migrations.AddField(
            model_name='mixturerecursive',
            name='nested',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary', to='recipes.Mixture'),
        ),
        migrations.AddField(
            model_name='mixturerecursive',
            name='primary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Mixture'),
        ),
    ]
