# Generated by Django 2.2.4 on 2019-10-30 13:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0020_extend_nested_mixture_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mixtureingredient',
            name='quantity',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1e-06)]),
        ),
    ]
